# Soring, searching, and counting

In [1]:
import numpy as np

In [ ]:
np.__version__

'1.11.2'

In [ ]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [2]:
x = np.array([[1,4],[3,1]])
x.sort()
print(x)

[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [5]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
y =np.lexsort((surnames, first_names))
print(y)

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
y = np.argsort(x)
print(y)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [9]:
x = np.random.permutation(10)
print("x =", x)
print("Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5")
np.partition(x,5)


x = [1 7 0 5 3 4 9 2 8 6]
Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5


array([2, 1, 0, 3, 4, 5, 6, 7, 8, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [15]:
x = np.random.permutation(10)
print("x =", x)
print("partitioned = ", np.partition(x,3))
print("indice = ", np.argpartition(x, 3))


x = [8 4 2 7 6 3 1 9 5 0]
partitioned =  [0 1 2 3 4 5 6 9 7 8]
indice =  [9 6 2 5 1 8 4 7 3 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [19]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)
print("maximum values = ", np.max(x, 1))
print("max indices = ", np.argmax(x, 1))
print("minimum values = ", np.min(x, 1))
print("min indices = ", np.argmin(x, 1))


x = [[7 6 0 8 3]
 [4 2 5 1 9]]
maximum values =  [8 9]
max indices =  [3 4]
minimum values =  [0 1]
min indices =  [2 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [21]:
x = np.array([[np.nan, 4], [3, 2]])
print("maximum values ignoring NaNs = ", np.nanmax(x, 1))
print("max indices = ", np.nanargmax(x, 1))
print("minimum values ignoring NaNs= ", np.nanmin(x, 1))
print("min indices = ", np.nanargmin(x, 1))

maximum values ignoring NaNs =  [4. 3.]
max indices =  [1 0]
minimum values ignoring NaNs=  [4. 2.]
min indices =  [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [23]:
x = np.array([[1, 2, 3], [1, 3, 5]])
print("Values bigger than 2 = ", x[x>2])
print("Their indices are ", np.nonzero(x>2))

Values bigger than 2 =  [3 3 5]
Their indices are  (array([0, 1, 1]), array([2, 1, 2]))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [25]:
x = np.array([[1, 2, 3], [1, 3, 5]])
y = np.flatnonzero(x)
print(y)

[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [29]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x > 0, x, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [30]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x, y, side = 'left')

array([0, 2, 1, 3])

## Counting

Q12. Get the number of nonzero elements in x.

In [33]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5